version: '3.6'

services:
  http_server:
    command: sleep infinity
    build:
      context: http_server
      target: test
    volumes:
      - ./http_server:/http_server
    ports:
      - "4567:4567"
